// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"todolist/internal/api"
	"todolist/internal/biz"
	"todolist/internal/dao"
	"todolist/internal/service"
	"todolist/ioc"
	"todolist/pkg/logger"
)

// Injectors from wire.go:

func InitApp() *gin.Engine {
	db := ioc.InitDB()
	userDao := dao.NewGORMUserDao(db)
	zapLogger := ioc.InitLogger()
	loggerLogger := logger.NewZapLogger(zapLogger)
	userBiz := biz.NewUserBiz(userDao, loggerLogger)
	userServiceInterface := service.NewUserService(userBiz, loggerLogger)
	userApi := api.NewUserApi(userServiceInterface, loggerLogger)
	engine := ioc.InitGin(userApi)
	return engine
}
